#!/usr/bin/env python3
"""Dashcam clip -> structured scene JSON -> Omniverse-ready USD stage."""

import argparse
import json
import sys
import textwrap
from pathlib import Path

from scene_extractor import extract_scene
from usd_builder import build_stage


def _write_readme(out_dir: Path, video: Path, scene) -> None:
    body = textwrap.dedent(f"""
    # Digital twin: `{video.name}`

    Generated by [nvidia_delrel/build_twin.py](../../build_twin.py) from the source clip
    `{video.name}`.

    **Summary:** {scene.summary}

    **Environment:** {scene.environment.road_type}, {scene.environment.weather},
    {scene.environment.time_of_day}, {scene.environment.lanes}-lane

    **Actors detected:** {len(scene.actors)}

    ## Files
    - `scene.json` — structured extraction from the NVIDIA hosted VLM
      (`nvidia/nemotron-3-nano-omni-30b-a3b-reasoning`).
    - `scene.usda` — human-readable USD stage. Opens in Omniverse USD Composer,
      Reality Composer Pro (macOS), Blender, or any USD-aware viewer.

    ## Open the twin
    - **macOS**: `open scene.usda` (uses Reality Composer Pro if installed).
    - **Omniverse**: `Open Stage...` in USD Composer / Kit.
    - **Programmatic**: `python -c "from pxr import Usd; Usd.Stage.Open('scene.usda')"`.
    """).lstrip()
    (out_dir / "README.md").write_text(body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("video", type=Path, help="Path to the dashcam clip")
    parser.add_argument(
        "-o", "--output", type=Path, default=None,
        help="Output directory (default: ./twins/<video_stem>/)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Run extraction only; print JSON and skip USD build",
    )
    args = parser.parse_args()

    if not args.video.is_file():
        print(f"error: {args.video} is not a file", file=sys.stderr)
        return 2

    print(f"[1/2] Extracting scene from {args.video.name} via NVIDIA VLM...", file=sys.stderr)
    try:
        scene = extract_scene(args.video)
    except (RuntimeError, ValueError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if args.dry_run:
        print(json.dumps(scene.model_dump(), indent=2))
        return 0

    out_dir = args.output or Path("twins") / args.video.stem
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "scene.json").write_text(json.dumps(scene.model_dump(), indent=2))
    print(f"      -> {out_dir / 'scene.json'} ({len(scene.actors)} actors)", file=sys.stderr)

    print(f"[2/2] Building USD stage...", file=sys.stderr)
    usd_path = build_stage(scene, out_dir / "scene.usda")
    print(f"      -> {usd_path}", file=sys.stderr)

    _write_readme(out_dir, args.video, scene)
    print(f"\nDone. Open in a viewer: open {usd_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
